import { Job } from '@/types'

export const FALLBACK_JOBS: Job[] = [
  { id: 'demo_1', title: 'Agricultural Program Manager', company: 'USDA Agricultural Research Service', location: 'Remote', salary_text: '$92k–$118k', salary_min: 92000, salary_max: 118000, salary_mid: 105000, type: 'Remote', source: 'usajobs', source_id: 'demo_1', posted_at: new Date().toISOString(), url: 'https://usajobs.gov', description: 'Lead federal agricultural research programs across the Midwest. Manage cross-functional teams of scientists and agronomists. Oversee $2M+ budgets. Six Sigma valued.', tags: ['USDA', 'Federal', 'Remote', 'Program Mgmt'], scores: { field: 95, salary: 92, location: 100, experience: 90, education: 92, total: 94 } },
  { id: 'demo_2', title: 'AgriTech Product Manager', company: 'Climate Corp (Bayer)', location: 'Remote', salary_text: '$100k–$130k', salary_min: 100000, salary_max: 130000, salary_mid: 115000, type: 'Remote', source: 'linkedin', source_id: 'demo_2', posted_at: new Date().toISOString(), url: 'https://linkedin.com/jobs', description: 'Own the product roadmap for precision agriculture software used by 10,000+ farmers. Manage cross-functional engineering and agronomy teams. Technology Management background ideal.', tags: ['AgriTech', 'Product Mgmt', 'Remote'], scores: { field: 90, salary: 100, location: 100, experience: 85, education: 96, total: 93 } },
  { id: 'demo_3', title: 'Food Systems Technology Manager', company: 'Cargill', location: 'Remote', salary_text: '$95k–$125k', salary_min: 95000, salary_max: 125000, salary_mid: 110000, type: 'Remote', source: 'adzuna', source_id: 'demo_3', posted_at: new Date().toISOString(), url: 'https://adzuna.com', description: 'Lead technology transformation across food and agriculture supply chain. Manage teams implementing ERP and AI-driven forecasting. Agricultural domain expertise plus tech management required.', tags: ['Food Systems', 'Supply Chain', 'Remote'], scores: { field: 88, salary: 98, location: 100, experience: 88, education: 96, total: 92 } },
  { id: 'demo_4', title: 'Sustainable Agriculture Project Manager', company: 'The Nature Conservancy', location: 'Remote / Columbia MO', salary_text: '$80k–$100k', salary_min: 80000, salary_max: 100000, salary_mid: 90000, type: 'Remote', source: 'indeed', source_id: 'demo_4', posted_at: new Date(Date.now() - 86400000).toISOString(), url: 'https://indeed.com/jobs', description: 'Manage sustainable agriculture projects across the Midwest. Coordinate with farmers, NGOs, and government agencies. Six Sigma valued.', tags: ['Sustainability', 'Agriculture', 'Columbia MO'], scores: { field: 90, salary: 85, location: 98, experience: 88, education: 86, total: 89 } },
  { id: 'demo_5', title: 'AgTech Operations Manager', company: 'Bayer Crop Science', location: 'St. Louis, MO (Hybrid)', salary_text: '$85k–$110k', salary_min: 85000, salary_max: 110000, salary_mid: 97500, type: 'Hybrid', source: 'linkedin', source_id: 'demo_5', posted_at: new Date().toISOString(), url: 'https://linkedin.com/jobs', description: 'Drive operational excellence across precision agriculture technology platforms. Lead teams deploying IoT sensors and farm management software.', tags: ['AgTech', 'Operations', 'Hybrid'], scores: { field: 92, salary: 88, location: 82, experience: 92, education: 88, total: 88 } },
  { id: 'demo_6', title: 'Rural Development Program Officer', company: 'USDA Rural Development', location: 'Columbia, MO', salary_text: '$72k–$90k', salary_min: 72000, salary_max: 90000, salary_mid: 81000, type: 'Onsite', source: 'usajobs', source_id: 'demo_6', posted_at: new Date().toISOString(), url: 'https://usajobs.gov', description: 'Administer USDA rural development programs in Missouri. Manage grant programs supporting agricultural businesses and rural infrastructure.', tags: ['USDA', 'Columbia MO', 'Federal'], scores: { field: 84, salary: 74, location: 100, experience: 86, education: 84, total: 84 } },
  { id: 'demo_7', title: 'Precision Agriculture Data Manager', company: 'CHS Inc.', location: 'Minneapolis, MN', salary_text: '$88k–$115k', salary_min: 88000, salary_max: 115000, salary_mid: 101500, type: 'Onsite', source: 'linkedin', source_id: 'demo_7', posted_at: new Date(Date.now() - 172800000).toISOString(), url: 'https://linkedin.com/jobs', description: 'Manage agricultural data platforms and analytics pipelines. Python, SQL, Power BI experience a strong plus.', tags: ['Data Mgmt', 'Precision Ag', 'Relocate'], scores: { field: 86, salary: 90, location: 62, experience: 84, education: 90, total: 83 } },
  { id: 'demo_8', title: 'Ag Extension Program Coordinator', company: 'University of Missouri Extension', location: 'Columbia, MO', salary_text: '$70k–$85k', salary_min: 70000, salary_max: 85000, salary_mid: 77500, type: 'Onsite', source: 'indeed', source_id: 'demo_8', posted_at: new Date().toISOString(), url: 'https://indeed.com/jobs', description: 'Coordinate agricultural extension programs for Missouri farmers. Develop training on technology adoption and crop management.', tags: ['Extension', 'Columbia MO', 'Agriculture'], scores: { field: 88, salary: 71, location: 100, experience: 85, education: 90, total: 85 } },
]
